export const PERMISSIONS = {
  DASHBOARD: {
    READ_DASHBOARD: "READ DASHBOARD",
    READ_DASHBOARD_ANALYTIC: "READ DASHBOARD ANALYTIC",
  },
  FAQS: {
    READ_FAQS: "READ FAQS",
    CREATE_FAQS: "CREATE FAQS",
    UPDATE_FAQS: "UPDATE FAQS",
    DELETE_FAQS: "DELETE FAQS",
  },
  USERS: {
    READ_USERS: "READ USERS",
    CREATE_USERS: "CREATE USERS",
    UPDATE_USERS: "UPDATE USERS",
    DELETE_USERS: "DELETE USERS",
  },
  ROLES: {
    READ_ROLES: "READ ROLES",
    CREATE_ROLES: "CREATE ROLES",
    UPDATE_ROLES: "UPDATE ROLES",
    DELETE_ROLES: "DELETE ROLES",
  },
  PERMISSIONS: {
    READ_PERMISSIONS: "READ PERMISSIONS",
    CREATE_PERMISSIONS: "CREATE PERMISSIONS",
    UPDATE_PERMISSIONS: "UPDATE PERMISSIONS",
    DELETE_PERMISSIONS: "DELETE PERMISSIONS",
  },
};
